---
title: "Different Graph Examples"
output: html_notebook
---

```{r}
library(ggplot2)
library(palmerpenguins)
my.data<-na.omit(penguins)
```

```{r}
str(my.data)
```

## Bargraph
```{r}
ggplot(my.data,aes(x=species,fill=sex))+
  geom_bar()
```
Barplot of averages
```{r}
spsex.avg<-aggregate(bill_length_mm~species+sex,data=my.data,FUN=mean) #get means for each species & sex

spsex.se<-aggregate(bill_length_mm~species+sex,data=my.data,FUN=function(x) sd(x)/sqrt(length(x))) #get standard error

#pull into one dataframe
bills.spsex<-cbind(spsex.avg,spsex.se$bill_length_mm)
colnames(bills.spsex)<-c("sps","sex","mean","se")

#plot
ggplot(bills.spsex,aes(x=sps,y=mean,fill=sex))+
  geom_bar(stat="identity",position=position_dodge(.9))+
  geom_errorbar(aes(ymax=mean + se, ymin=mean-se),width=0.2,position=position_dodge(.9))+
  scale_fill_manual(values=c("female" = "light blue","male"="royal blue"), drop = FALSE)+
  scale_x_discrete(limits=levels(bills.spsex$sps))+
  scale_y_continuous(breaks=seq(0,60,5),expand = c(0, 0),lim=c(0,60))+
  labs(x="",y="Bill Length (mm)")+
  theme(legend.position = "bottom",legend.text=element_text(size=12),legend.title=element_blank()) + #extra to make it pretty
  theme(panel.background = element_blank())+
  #theme(text = element_text(family = "Times New Roman"))+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"))
```

## Boxplot
```{r}
ggplot(my.data,aes(x=species,y=body_mass_g,fill=sex))+
  geom_boxplot()
```
```{r}
ggplot(my.data, aes(x = species, y = flipper_length_mm)) +
  geom_boxplot(aes(color = species), width = 0.3, show.legend = FALSE) +
  geom_jitter(aes(color = species), alpha = 0.5, show.legend = FALSE, position = position_jitter(width = 0.2, seed = 0)) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(x = "Species",y = "Flipper length (mm)")
```


## Scatterplot
```{r}
ggplot(my.data,aes(x=flipper_length_mm,y=bill_length_mm))+
  geom_point()
```

```{r}
ggplot(my.data, aes(x = bill_length_mm, y = bill_depth_mm,group = species)) +
  geom_point(aes(color = species, shape = species),size = 3,alpha = 0.8) +
  geom_smooth(method = "lm", se = FALSE, aes(color = species)) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Penguin bill dimensions",
       subtitle = "Bill length and depth for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Bill length (mm)",
       y = "Bill depth (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme(legend.position = "right")

```


## Histogram
```{r}
ggplot(my.data, aes(x = flipper_length_mm)) +
  geom_histogram(aes(fill = species), alpha = 0.5, position = "identity") +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) +
  labs(x = "Flipper length (mm)",y = "Frequency",title = "Penguin flipper lengths")

```
## Time Series
```{r}
head(economics)

ggplot(economics, aes(x = date, y = pop))+
  geom_line()
```

